### PR TITLE
support for . notation

### PR DESCRIPTION
**Pull request by ShreyashKira**
I just tried to make . notation support would like you to review it.

### CODE REVIEW

**Comment by Snowflake107** [comment]
Thanks

**Comment by ShreyashKira** [comment]
BTW it's my first pr 😅 so pls stay soft with me.
I also made this for the pull, push, get, and add. I will add them slowly to my fork master branch.

**Comment by Snowflake107** [comment]
hm, that's a good idea but can you do it on alpha branch instead?

**Comment by ShreyashKira** [comment]
> hm, that's a good idea but can you do it on alpha branch instead?

oh sorry, there is nothing like contribution guidelines so I m not sure where to pull it.

**Comment by Snowflake107** [comment]
I've changed the base branch

**Comment by ShreyashKira** [comment]
yeah i see.

**Pull request merged**
